# Generated by Django 2.1.15 on 2021-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loandetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('loan_no', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('loan_tenure', models.IntegerField()),
                ('loan_roi', models.FloatField()),
                ('loan_date', models.DateField()),
                ('surety_no', models.IntegerField()),
                ('surety_name', models.CharField(max_length=30)),
            ],
        ),
    ]
