# Generated by Django 2.2 on 2021-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0002_auto_20211012_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('memberno', models.IntegerField()),
                ('memebername', models.CharField(max_length=30)),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
