# Generated by Django 2.2 on 2021-10-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0003_memberdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetails',
            name='mobileno',
            field=models.CharField(max_length=30),
        ),
    ]
