# Generated by Django 2.2 on 2021-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0004_auto_20211020_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiledetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('membername', models.CharField(max_length=30)),
                ('memberno', models.IntegerField()),
                ('memberclass', models.CharField(max_length=20)),
                ('employeecode', models.CharField(max_length=20)),
                ('soceityname', models.CharField(max_length=20)),
            ],
        ),
    ]
