# Generated by Django 2.2 on 2021-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0005_profiledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('transactionmode', models.CharField(max_length=30)),
                ('heading', models.CharField(max_length=30)),
                ('receiotorcharges', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
